# Generated by Django 5.2.4 on 2025-07-07 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0003_alter_productmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='completed',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
